### ISSUE TITLE
Blog 초기화

### ISSUE THREAD

**Issue by DaehunGwak** [DaehunGwak/daehungwak.github.io#1]
### TODO

- [x] Blog 초기화
- [x] gh-pages 연동
- [x] 초기 프로필 세팅
- [ ] 더미 포스트 작성
- [ ] slug 문제 해결

### References

- https://perade.github.io/blog/make-blog-with-gridsome-2nd/
